version: '3'
networks:
  monitor-net:
    driver: bridge

volumes:
    grafana_data: {}
    influxdb_data:  {}
services:
     grafana:
       image: grafana/grafana:5.4.3
       container_name: grafana
       volumes:
         - grafana_data:/var/lib/grafana
         - ./datasources:/etc/grafana/provisioning/datasources/
         - ./dashboards:/etc/grafana/provisioning/dashboards/
       user: root
       environment:
         - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
         - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
         - GF_USERS_ALLOW_SIGN_UP=false
         - GF_PANELS_DISABLE_SANITIZE_HTML=true
       restart: unless-stopped
       expose:
         - 3000
       ports:
         - 3000:3000
       networks:
         - monitor-net

     influxdb:
       image: influxdb:1.8
       container_name: influxdb
       volumes:
         - influxdb_data:/var/lib/influxdb
       environment:
         - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME:-admin}
         - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD:-admin}q
         - INFLUXDB_BIND_ADRESS=:8088
         - INFLUXDB_DB=converter
       restart: unless-stopped
       ports:
         - 8086:8086
         - 8088:8088
         - 25826:25826/udp
       expose:
         - 8086
         - 8088
       networks:
         - monitor-net

     jmeter:
       build:
         context: ./jmeter
         dockerfile: jmeter.dockerfile
       container_name: jmeter
       volumes:
         - ./jmeter/script:/scripts
       entrypoint:
         - /jmeter/apache-jmeter-5.2.1/bin/jmeter
         - -n
         - -t
         - /scripts/convert_BTC_to_UAH.jmx
       networks:
         - monitor-net
         




